variables:
  PROJECT: egapro
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  DEV_NAMESPACE_ENVIRONMENT: "egapro-dev"
  MASTER_NAMESPACE_ENVIRONMENT: "master"
  PREPROD_NAMESPACE_ENVIRONMENT: "preprod"
  PROD_NAMESPACE_ENVIRONMENT: "prod"
  ENABLE_PERSISTENT_VOLUME: "false"
  LIFETIME: "permanent"
  LETS_ENCRYPT_ISSUER: "letsencrypt-prod"
  STARTUP: "egapro"
  APP_DOMAIN_NAME: "dev.fabrique.social.gouv.fr"
  # Rancher project id
  RANCHER_PROJECT_ID: c-kk8xm:p-zqfvb
  RANCHER_PROJECT_ID_PROD: c-l9h59:p-jcmhs
  # Docker Image Version
  DOCKER_VERSION: "18.06"
  INFRA_GIT_DEPLOY_VERSION: "1.0"
  NODE_VERSION: "10"
  INFRA_CURL_VERSION: "1.0"
  HELM_VERSION: "0.20.0"
  KUBECTL_VERSION: "0.7.0"
  KINTO_VERSION: "13.1.1"
  MEMCACHED_VERSION: "1.5.12-alpine"
  POSTGRES_VERSION: "11-debian-9"
  POSTGRES_JOB_VERSION: "11-alpine"
  # Helm Chart Version
  POSTGRES_CHART_VERSION: "6.5.6"
  MEMCACHED_CHART_VERSION: "3.1.0"
  # Ports
  APP_PORT: 9000
  API_PORT: 4000
  KINTO_PORT: 8888
  # Quotas api
  API_RESOURCE_CPU_LIMIT: "50m"
  API_RESOURCE_MEMORY_LIMIT: "32Mi"
  API_RESOURCE_CPU_REQUEST: "5m"
  API_RESOURCE_MEMORY_REQUEST: "16Mi"
  # Quotas app
  APP_RESOURCE_CPU_LIMIT: "50m"
  APP_RESOURCE_MEMORY_LIMIT: "32Mi"
  APP_RESOURCE_CPU_REQUEST: "5m"
  APP_RESOURCE_MEMORY_REQUEST: "16Mi"
  # Quotas Kinto
  KINTO_RESOURCE_CPU_LIMIT: "100m"
  KINTO_RESOURCE_MEMORY_LIMIT: "128Mi"
  KINTO_RESOURCE_CPU_REQUEST: "10m"
  KINTO_RESOURCE_MEMORY_REQUEST: "32Mi"
  # Quotas job init Kinto
  INIT_KINTO_RESOURCE_CPU_LIMIT: "20m"
  INIT_KINTO_RESOURCE_MEMORY_LIMIT: "16Mi"
  INIT_KINTO_RESOURCE_CPU_REQUEST: "10m"
  INIT_KINTO_RESOURCE_MEMORY_REQUEST: "8Mi"
  # Quotas Memcached
  MEMCACHED_RESOURCE_CPU_LIMIT: "50m"
  MEMCACHED_RESOURCE_MEMORY_LIMIT: "64Mi"
  MEMCACHED_RESOURCE_CPU_REQUEST: "10m"
  MEMCACHED_RESOURCE_MEMORY_REQUEST: "32Mi"
  POSTGRES_RESOURCE_CPU_LIMIT: "50m"
  POSTGRES_RESOURCE_MEMORY_LIMIT: "256Mi"
  POSTGRES_RESOURCE_CPU_REQUEST: "25m"
  POSTGRES_RESOURCE_MEMORY_REQUEST: "128Mi"
