---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: egapro-api${HASH_BRANCH_NAME}
  labels:
    app: egapro-api${HASH_BRANCH_NAME}
    branch: egapro${HASH_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egapro-api${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: egapro-api${HASH_BRANCH_NAME}
    spec:
      containers:
        - image: ${EGAPRO_REGISTRY}/api:${IMAGE_TAG}
          name: egapro-api
          ports:
            - containerPort: ${PORT}
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/version
              port: ${PORT}
            initialDelaySeconds: 3
            periodSeconds: 5
          env:
            - name: API_PORT
              value: "${PORT}"
            - name: KINTO_SERVER
              value: "kinto${HASH_BRANCH_NAME}"
            - name: KINTO_BUCKET
              value: "egapro"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: KINTO_ADMIN_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: KINTO_ADMIN_PASSWORD
            - name: MAIL_USE_TLS
              value: "true"
            - name: MAIL_PORT
              value: "465"
            - name: MAIL_FROM
              value: "Index EgaPro <contact@egapro.beta.gouv.fr>"
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: MAIL_PASSWORD
            - name: API_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: egapro-secret
                  key: API_SENTRY_DSN
            - name: API_SENTRY_ENVIRONMENT
              value: "development"
