kind: ConfigMap
apiVersion: v1
metadata:
  name: egapro
data:
  EGAPRO_PROCONNECT_SCOPE: "openid email profile organizations phone"
  EGAPRO_PROCONNECT_DISCOVERY_URL: "auth.agentconnect.gouv.fr"
  EGAPRO_PROCONNECT_SIGN_IN_URL: "auth.agentconnect.gouv.fr/users/start-sign-in"
  EGAPRO_PROCONNECT_MANAGE_ORGANISATIONS_URL: "auth.agentconnect.gouv.fr/manage-organizations"
  EGAPRO_PROCONNECT_PERSONAL_INFORMATION_URL: "auth.agentconnect.gouv.fr/personal-information"
