kind: ConfigMap
apiVersion: v1
metadata:
  name: egapro
data:
  EGAPRO_PROCONNECT_SCOPE: "openid email profile organizations phone"
  EGAPRO_PROCONNECT_DISCOVERY_URL: "https://identite.proconnect.gouv.fr"
  EGAPRO_PROCONNECT_SIGN_IN_URL: "https://identite.proconnect.gouv.fr/users/start-sign-in"
  EGAPRO_PROCONNECT_MANAGE_ORGANISATIONS_URL: {{ if eq .Values.global.env "prod" }}"https://identite.proconnect.gouv.fr/manage-organizations"{{ else }}"https://app-fca.integ01.dev-agentconnect.fr/manage-organizations"{{ end }}
  EGAPRO_PROCONNECT_PERSONAL_INFORMATION_URL: "https://identite.proconnect.gouv.fr/personal-information"
