apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files-public
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - {{ .Values.global.host }}
    secretName: api-crt
  rules:
  {{ range $fileName := .Values.files.public }}
  - host: {{ $.Values.global.host }}
    http:
      paths:
      - path: /{{ $fileName }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: files
            port:
              number: 80

    {{ end }}
