projectName: egapro
repositoryName: egapro
dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique

environmentPatterns:
  prod: false
  dev: "!v*"

webhhookMountSecrets:
  - mattermost-webhook