name: ♻️ Deactivate
on:
  pull_request:
    types: [closed]
  delete:
    branches:
      - "**"
      - "!v*"
      - "!master"
      - "!alpha"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.ref || github.event.pull_request.head.ref }}

jobs:
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-deactivate-atlas.yaml@v1
    secrets: inherit
